### ISSUE TITLE
Don't change example code after run

### ISSUE THREAD

**Issue by fraya** [cgay/web-playground#17] opened 2020-12-09 06:47 UTC
After running a first example, if I choose another example, the code textfield does not change.

Firefox 83.0 (Linux 64 bits)

**Comment by cgay** [comment] 2020-12-09 16:16
I'll take a look. I've only used Chrome so far and this works fine there. To be clear, I did this:

1. go to a fresh playground (contains hello world code)
2. choose an example
3. click Run button
4. choose a different example

**Comment by fraya** [comment] 2020-12-09 18:40
Now It's working with Firefox. Tested in Chromium and works too.
I didn't change anything. Did you?

**Comment by cgay** [comment] 2020-12-09 18:42
Nope. It's possible it's related to the funky way I have my dev instance deployed. I noticed that at one point it didn't respond until I foregrounded the emacs I have it running in. :-)

Going to close this for now since I can't reproduce it on Safari or Firefox on Mac either.

**Comment by cgay** [comment] 2020-12-09 18:43
Wait, was this a problem with the dev instance or play.opendylan.org?

**Comment by fraya** [comment] 2020-12-09 18:45
dev instance

**Comment by cgay** [comment] 2020-12-09 18:47
ok, closing. thanks.

**Closed as completed by cgay** 2020-12-09 18:47 UTC
